config/routes.rb
Rails.application.routes.draw do
  get 'cpc/_cpc'
  get 'cpc/index'
  get 'cpc/edit'
  get 'cpc/show'
  get 'cpc/create'
  get 'sogou_ideas/edit'
  get 'sogou_ideas/index'
  get 'sogou_ideas/new'
  get 'sogou_ideas/show'
  get 'sogou_ideas/_sogou_idea'
  get 'sogou_groups/edit'
  get 'sogou_groups/index'
  get 'sogou_groups/new'
  get 'sogou_groups/show'
  get 'sogou_plans/edit'
  get 'sogou_plans/index'
  get 'sogou_plans/new'
  get 'sogou_plans/show'
  get 'sogou_plans/_form'
  get 'sogou_plans/new'
  get 'sogou_plans/show'
  get 'sogou_plans/index'
  get 'sogou_plans/edit'
  
  post '/send_demo_email' => 'home#send_demo_email'
  post '/send_contact_us_email' => 'home#send_contact_us_email'
  
  get '/dashboard' => 'home#dashboard'
  
  require 'sidekiq/web'

  authenticate :user, lambda { |u| u.superadmin_role? } do
  mount Sidekiq::Web => "/sidekiq"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  resources :campaigns
  resources :accounts
  resources :adgroups
  resources :keywords

  resources :sogou_plans
  resources :sogou_groups
  resources :sogou_ideas
  resources :cpcs
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  scope "/superadmin" do
    resources :users
  end

  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  # 360's actions 

  get 'accounts/:id/retrieve_campaigns' => 'accounts#retrieve_campaigns', as: :accounts_retrieve_campaigns
  get 'campaigns/:id/retrieve_adgroups' => 'campaigns#retrieve_adgroups', as: :campaigns_retrieve_adgroups
  get 'adgroups/:id/retrieve_keywords' => 'adgroups#retrieve_keywords', as: :adgroup_retrieve_keywords
  get 'accounts/:id/delete_campaigns' => 'accounts#delete_campaigns', as: :accounts_delete_campaigns
  get 'campaigns/:id/delete_adgroups' => 'campaigns#delete_adgroups', as: :campaigns_delete_adgroups
  get 'adgroups/:id/delete_keywords' => 'adgroups#delete_keywords', as: :adgroup_delete_keywords
  get 'superadmin/:id/make_superadmin' => 'users#make_superadmin', as: :make_superadmin

  # sogou's actions

  get 'accounts/:id/retrieve_plans' => 'accounts#sogou_retrieve_plans', as: :accounts_retrieve_plans
  get 'accounts/:id/delete_plans' => 'accounts#delete_plans', as: :accounts_delete_plans
  get 'sogou_plans/:id/retrieve_groups' => 'sogou_plans#sogou_retrieve_groups', as: :sogou_retrieve_groups
  get 'sogou_plans/:id/delete_groups' => 'sogou_plans#sogou_delete_groups', as: :sogou_delete_groups
  get 'sogou_groups/:id/retrieve_ideas' => 'sogou_groups#sogou_retrieve_ideas', as: :sogou_retrieve_ideas
  get 'sogou_groups/:id/delete_ideas' => 'sogou_groups#sogou_delete_ideas', as: :sogou_delete_ideas
  get 'sogou_groups/:id/retrieve_cpcs' => 'sogou_groups#sogou_retrieve_cpcs', as: :sogou_retrieve_cpcs
  get 'sogou_groups/:id/delete_cpcs' => 'sogou_groups#sogou_delete_cpcs', as: :sogou_delete_cpcs
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.superadmin_role?
          can :manage, :all
          can :access, :rails_admin       # only allow admin users to access Rails Admin
          can :dashboard                  # allow access to dashboard
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :campaigns, :dependent => :destroy
  has_many :sogou_plans, :dependent => :destroy
  serialize :group_id_array, Array
end

app/models/adgroup.rb
class Adgroup < ApplicationRecord
  belongs_to :campaign
  has_many :keywords, dependent: :destroy
  paginates_per 2
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :account
  has_many :adgroups, dependent: :destroy
end

app/models/cpc.rb
class Cpc < ApplicationRecord
	belongs_to :sogou_group
end

app/models/create_sogou_plan.rb
class CreateSogouPlan < ApplicationRecord
end

app/models/keyword.rb
class Keyword < ApplicationRecord
  belongs_to :adgroup
end

app/models/sogou_group.rb
class SogouGroup < ApplicationRecord
  belongs_to :sogou_plan
      #   t.text :negative_words
      # t.text :exact_negative_words
  serialize :negative_words, Array
  serialize :exact_negative_words, Array
  has_many :sogou_ideas, dependent: :destroy
  has_many :cpcs, dependent: :destroy
end

app/models/sogou_idea.rb
class SogouIdea < ApplicationRecord
	belongs_to :sogou_group
	
end

app/models/sogou_plan.rb
class SogouPlan < ApplicationRecord
	belongs_to :account
	serialize :schedule, Array
	has_many :sogou_groups, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :accounts, dependent: :destroy
end

app/controllers/cpc_controller.rb
class CpcController < ApplicationController
  before_action :find_cpc, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :owned_cpc, only: [:show, :edit, :update, :destroy]

  def new
    @sogou_cpc = Cpc.new
  end

  def create
    @sogou_cpc = Cpc.new(sogou_cpc_params)
  end

  def new
  end

  def show
  end

  def destroy
    session[:return_to] ||= request.referer
    @sogou_cpc.destroy
    respond_to do |format|
      format.html { redirect_to session.delete(:return_to), notice: 'CPC was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

   private 
    def find_cpc
      @sogou_cpc = Cpc.find(params[:id])
    end

    def owned_cpc
      unless current_user.id == @sogou_cpc.sogou_group.sogou_plan.account.user_id
      redirect_to root_path
      end
    end
     def sogou_cpc_params
      params.require(:sogou_group).permit(:cpc_id, :cpc_grp_id, :cpc, :price, :visit_url, :match_type, :cpc_quality, :pause, :status, :is_show, :opt,'@xmlns:ns2')
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/adgroups_helper.rb
module AdgroupsHelper
  end

app/helpers/campaigns_helper.rb
module CampaignsHelper
  def get_account_campaigns(accounts)
    @campaigns = []
      accounts.each do |account|
        account.campaigns.each do |campaign|
          @campaigns.push(campaign)
          end
      end

      if @campaigns.count >0
          @campaigns.each_with_index do |campaign, index|
          end
      end
  end
end

app/helpers/cpc_helper.rb
module CpcHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer-container">
  <div class="container">
    <div class="row" >
      <div class="col-xs-12">
        <p class="color-xs-white text-center">Copyright © 2016 Adeqo. <a href="http://www.bmgww.com/" target="_blank">Adeqo & Adeqo Limited are Intellectual Property of Beyond Media Global Limited.</a>. All Rights Reserved. ICP: 15044856.</p>
        <p class="color-xs-white text-center">Terms of use &amp; Privacy Policy</p>
      </div>
      <!-- <div class="col-xs-12">
        <p class="color-xs-white text-center">Terms of use &amp; Privacy Policy</p>
      </div> -->
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default navbar-fixed-top navbar-transparent" data-spy="affix" data-offset-top="160">
    
    <div class="bg-black color-xs-white line-height-xs-30">
      <div class="container">
        <div class="row">
          <div class="col-xs-4 padding-right-xs-0"><i class="fa fa-phone" aria-hidden="true"></i> +852 2492 2770</div>
          <div class="col-xs-8 padding-left-xs-0 padding-right-sm-0 pull-right">
            <ul class="list-inline list-unstyled margin-xs-0 text-right text-uppercase">
              <li><a class="color-xs-white padding-left-xs-0 padding-right-xs-0 padding-left-sm-30 padding-right-sm-30" href="contact_us">Contact Us</a></li>
              <li><a class="color-xs-white padding-left-xs-0 padding-right-xs-0 padding-left-sm-30 padding-right-sm-30" href="#">Support</a></li>
              <li><%= link_to "Login", new_user_session_path, class: "color-xs-white padding-left-xs-0 padding-right-xs-0 padding-left-sm-30 padding-right-sm-30", data: { toggle: "modal", target: "#loginModal"} %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    
    <div class="container">
      <div class="">
        <div class="navbar-header">
          <button type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar" class="navbar-toggle collapsed"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
          <a href="/" class="navbar-brand"><%= image_tag "adeqo-logo.png", alt: "Adeqo", title: "Adeqo" %></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right text-uppercase">
            <!-- <li><a href="/"><i>Home</i></a></li> -->
            <li class="dropdown">
              <!-- <a href="/#" class="dropdown-toggle disable" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i>Features</i> <span class="caret"></span></a> -->
              <ul class="dropdown-menu pull-left text-uppercase">
                <!-- <li><a href="/services/search_engine_marketing"><i>Search Engine Marketing</i></a></li>
                <li><a href="/services/search_engine_optimization"><i>Search Engine Optimization</i></a></li>
                <li><a href="/services/social_media_marketing"><i>Social Media Marketing</i></a></li>
                <li><a href="/services/content_localisation"><i>Content Localization</i></a></li> -->
                
                <li><a href="#"><i>Real Time China</i></a></li>
                <li><a href="#"><i>ROI Tracking</i></a></li>
                <li><a href="#"><i>Actionable Insights</i></a></li>
                <li><a href="#"><i>Data Visualization</i></a></li>
                <li><a href="#"><i>Cross Channel</i></a></li>
              </ul>
            </li>
            <li><a href="/pricing"><i>Pricing</i></a></li>
            <li><a href="/demo"><i>Request Demo</i></a></li>
            <!-- <li><a href="/demo"><i>FREE CONSULTATION</i></a></li> -->
            <li><a href="http://blog.adeqo.com/"><i>Blog</i></a></li>
            <!-- <li><a href="/contact_us"><i>Contact Us</i></a></li> -->
            <!-- <li><a onclick="showModal('login');"><i>Login</i></a></li> -->
          </ul>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_site_footer.html.erb
<footer class="footer">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
      <p id="footer-text">© 2018 Beyond Media Global Limited. All Rights Reserved. ICP: 15044856</p>
    </div>
  </div>
</footer>

app/views/layouts/_site_header.html.erb
<header class="navbar navbar-default" role="navigation" id="my-nav">
  <nav>
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button id="hamburger-button" type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to(image_tag('adeqo-logo.png', class: "nav navbar navbar-left", id: "logo-image"), "/") %></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul id="my-navigation" class="nav navbar-nav navbar-right">
          <% if current_user && current_user.superadmin_role? %>
            <li><%= link_to 'Manage Users', users_path %> </li>
            <li> <div id="menu-separator">| </div></li>
          <% end%>

          <% if user_signed_in? %>
            <li><%= link_to 'Dashboard', dashboard_path %></li>
            <li><%= link_to 'My accounts', accounts_path %></li>
            <!-- <li><%= link_to 'My campaigns', campaigns_path %></li> -->
            <!-- <li><%= link_to 'My adgroups', adgroups_path %></li> -->
            <!-- <li><%= link_to 'My keywords', keywords_path %></li> -->
            <li> <div id="menu-separator">| </div></li>
            <li><%= link_to 'Adeqo Account', edit_user_registration_path %></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
          <% else%>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <% end %>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adeqo</title>
    <%= csrf_meta_tags %>

    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <%= render "users/sessions/new" %>
    </div>

    <div class="modal fade" id="signupModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <%= render "users/registrations/new" %>
    </div>

    <div class="modal fade" id="forgotModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <%= render "users/passwords/new" %>
    </div>

  </body>
</html>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adeqo</title>
    <%= csrf_meta_tags %>

    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag    'site', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'site', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/site_header" %>
    <%= yield %>
    <div class="footer-top"></div>
    <%= render "layouts/site_footer" %>
  </body>
</html>